export const mainMenuItems = [
  { to: "/", label: "Home" },
  { to: "/astro/ui", label: "Astro", reload: true },
  {
    to: "/astro/compatibility",
    label: "Compatibility Protocols",
    reload: true,
  },
  { to: "/astro/pp-table", label: "5 Pakṣi Table", reload: true },
  { to: "/astro/json-grid", label: "API Testing",  size: 'small', reload: true },
  { to: "/users", label: "Members and Admins" },
  { to: "/user-blocks", label: "Blocked users", size: "small" },
  { to: "/reported-users", label: "Reported users", size: "small" },
  { to: "/messages", label: "Messages", size: "small" },
  { to: "/dictionary", label: "Dictionary", icon: "book-alphabet" },
  { to: "/snippets", label: "Snippets" },
  { to: "/settings", label: "Settings" },
  { to: "/charts", label: "Chart List" },
  { to: "/tech", label: "Files & Planetary Stations" },
  { to: "/ip-whitelist", label: "IP Whitelist" },
];
