const rashiValues = [
  {
    num: 1,
    key: "ar",
    ruler: "ma",
    en: "aries",
    icon: "♈︎",
    element: "fire",
    mobility: "movable",
  },
  {
    num: 2,
    key: "ta",
    ruler: "ve",
    en: "taurus",
    icon: "♉︎",
    element: "earth",
    mobility: "fixed",
  },
  {
    num: 3,
    key: "ge",
    ruler: "me",
    en: "gemini",
    icon: "♊︎",
    element: "air",
    mobility: "dual",
  },
  {
    num: 4,
    key: "ca",
    ruler: "mo",
    en: "cancer",
    icon: "♋︎",
    element: "water",
    mobility: "movable",
  },
  {
    num: 5,
    key: "le",
    ruler: "su",
    en: "leo",
    icon: "♌︎",
    element: "fire",
    mobility: "fixed",
  },
  {
    num: 6,
    key: "vi",
    ruler: "me",
    en: "virgo",
    icon: "♍︎",
    element: "earth",
    mobility: "dual",
  },
  {
    num: 7,
    key: "li",
    ruler: "ve",
    en: "libra",
    icon: "♎︎",
    element: "air",
    mobility: "movable",
  },
  {
    num: 8,
    key: "sc",
    ruler: "ma",
    en: "scorpio",
    icon: "♏︎",
    element: "water",
    mobility: "fixed",
  },
  {
    num: 9,
    key: "sa",
    ruler: "ju",
    en: "sagittarius",
    icon: "♐︎",
    element: "fire",
    mobility: "dual",
  },
  {
    num: 10,
    key: "cp",
    ruler: "sa",
    en: "capricorn",
    icon: "♑︎",
    element: "earth",
    mobility: "movable",
  },
  {
    num: 11,
    key: "aq",
    ruler: "sa",
    en: "aquarius",
    icon: "♒︎",
    element: "air",
    mobility: "fixed",
  },
  {
    num: 12,
    key: "pi",
    ruler: "ju",
    en: "pisces",
    icon: "♓︎",
    element: "water",
    mobility: "dual",
  },
];

export default rashiValues;
